//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Questionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person_Questionnaire()
        {
            this.Person_Questionnaire_Result = new HashSet<Person_Questionnaire_Result>();
        }
    
        public int Questionnaire_ID { get; set; }
        public string Person_ID { get; set; }
        public System.DateTime Answer_Date { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Questionnaire_Result> Person_Questionnaire_Result { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual Registered_Person Registered_Person { get; set; }
    }
}
