//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Possible_Answer
    {
        public int Possible_Answer_Seq { get; set; }
        public string Answer_Text { get; set; }
        public int Question_Seq { get; set; }
        public int Display_Order { get; set; }
    
        public virtual Question_Bank Question_Bank { get; set; }
    }
}
