//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPasswordRequest
    {
        public System.Guid Id { get; set; }
        public string Person_ID { get; set; }
        public Nullable<System.DateTime> ResetRequestDateTime { get; set; }
    
        public virtual Registered_Person Registered_Person { get; set; }
    }
}
