//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building_Floor
    {
        public int Building_Floor_ID { get; set; }
        public Nullable<int> Campus_ID { get; set; }
        public Nullable<int> Building_ID { get; set; }
        public string Floor_Name { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Campus Campu { get; set; }
    }
}
