//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calender_Rules
    {
        public int Calender_Rules_Seq { get; set; }
        public System.TimeSpan Time_Open { get; set; }
        public System.TimeSpan Time_Closed { get; set; }
        public int Campus_ID { get; set; }
        public int Period_Type_ID { get; set; }
        public string Day_Of_Week_ID { get; set; }
    
        public virtual Day_Of_Week Day_Of_Week { get; set; }
        public virtual Period_Type Period_Type { get; set; }
        public virtual Campus Campu { get; set; }
    }
}
