//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Problem
    {
        public int Common_Problem_ID { get; set; }
        public string Common_Problem_Name { get; set; }
        public string Description { get; set; }
        public int Common_Problem_Type_ID { get; set; }
    
        public virtual Common_Problem_Type Common_Problem_Type { get; set; }
    }
}
