//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Access_Log
    {
        public int Log_Seq { get; set; }
        public System.DateTime Access_DateTime { get; set; }
        public int Session_ID { get; set; }
        public int Document_Seq { get; set; }
    
        public virtual Person_Session_Log Person_Session_Log { get; set; }
        public virtual Document_Repository Document_Repository { get; set; }
    }
}
