//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    
    public partial class findBookingVenues_Result1
    {
        public int Campus_ID { get; set; }
        public int Building_ID { get; set; }
        public int Building_Floor_ID { get; set; }
        public int Venue_ID { get; set; }
        public string Venue_Name { get; set; }
        public string Venue_Type { get; set; }
    }
}
