//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Role
    {
        public int Person_Role_ID { get; set; }
        public int Active_Ind { get; set; }
        public string Person_ID { get; set; }
        public int Role_ID { get; set; }
        public int Level_ID { get; set; }
    
        public virtual Person_Level Person_Level { get; set; }
        public virtual Registered_Person Registered_Person { get; set; }
        public virtual Role Role { get; set; }
    }
}
