//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Session_Action_Log
    {
        public int Action_Log_Seq { get; set; }
        public System.DateTime Action_DateTime { get; set; }
        public int Session_ID { get; set; }
        public int Action_ID { get; set; }
        public string Action_Performed { get; set; }
        public string Crud_Operation { get; set; }
    
        public virtual Person_Session_Log Person_Session_Log { get; set; }
        public virtual Action Action { get; set; }
    }
}
