//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Action
    {
        public int Create_Ind { get; set; }
        public int Read_Ind { get; set; }
        public int Update_Ind { get; set; }
        public int Delete_Ind { get; set; }
        public int Action_ID { get; set; }
        public int Role_ID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Role Role { get; set; }
    }
}
