//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue_Characteristic
    {
        public int Characteristic_ID { get; set; }
        public int Venue_ID { get; set; }
        public int Building_Floor_ID { get; set; }
        public int Building_ID { get; set; }
        public int Campus_ID { get; set; }
        public int Quantity { get; set; }
        public string Additional_Information { get; set; }
    
        public virtual Characteristic Characteristic { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
