//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue_Problem
    {
        public int Problem_Seq { get; set; }
        public System.DateTime DateTime_Logged { get; set; }
        public string Person_ID_Logged { get; set; }
        public string Description { get; set; }
        public int Common_Problem_Type_ID { get; set; }
        public string Status { get; set; }
        public System.DateTime DateTime_Closed { get; set; }
        public string Person_ID_Closed { get; set; }
        public int Venue_ID { get; set; }
        public int Building_Floor_ID { get; set; }
        public int Building_ID { get; set; }
        public int Campus_ID { get; set; }
    
        public virtual Common_Problem_Type Common_Problem_Type { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual Registered_Person Registered_Person { get; set; }
        public virtual Registered_Person Registered_Person1 { get; set; }
    }
}
