//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAssistantApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue_Booking_Person
    {
        public string Person_ID { get; set; }
        public int Venue_Booking_Seq { get; set; }
        public string Attendee_Type { get; set; }
        public string Attendee_Status { get; set; }
    
        public virtual Attendee_Status Attendee_Status1 { get; set; }
        public virtual Attendee_Type Attendee_Type1 { get; set; }
        public virtual Registered_Person Registered_Person { get; set; }
        public virtual Venue_Booking Venue_Booking { get; set; }
    }
}
